---
title: "ASL AF calcs"
author: "Abby Lewis"
date: "2022-08-29"
output: html_document
---

Using two layers

Step 1: Load data and packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(rLakeAnalyzer)
library(openair)

#Load data and stratification boundaries. This file is created by "03 - Stratified avgs.Rmd"
full_with_thermo <- read.csv("../Compiled data/Stratified_period_data_with_thermo.csv")%>%
  mutate(Date=as.Date(Date))
#Load lake metadata
lat_long <- read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/fadd3eaa25b5fdd1fc4efba70e660579")
```


Step 2: Calculate VW DO
```{r}
#prepare bathymetry
#lake with only one method (data/model)
lake_bats <- read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/ba733454c29a5f026efed05a6e6ef75b")%>%
  filter(Area_m2>0)%>%
  group_by(LakeID)%>%
  mutate(methods_n = length(unique(Method)))%>%
  filter(methods_n==1|Method=="data")%>%
  ungroup()

#Check bathymetric data availability
unique(lake_bats$LakeID)[!unique(lake_bats$LakeID)%in%unique(lat_long$LakeID)]
unique(lat_long$LakeID)[!unique(lat_long$LakeID)%in%unique(lake_bats$LakeID)] #missing full bathymetry for 37 lakes

#Total n to start: 609
length(unique(full_with_thermo$LakeID))

#Calculate volume-weighted oxygen concentrations
vw_do <- full_with_thermo%>%
  full_join(lake_bats, by = c("LakeID","Depth_m"))%>%
  filter(!is.na(IntervalVolume_m3))%>%
  filter(Depth_m>hypo_depth)%>%
  mutate(DO_mass = DO_mgL*IntervalVolume_m3,
         Temp_total = Temp_C*IntervalVolume_m3,
         Year = year(Date),
         breakpoint = (MaximumDepth_m - hypo_depth)/2 + hypo_depth,
         hypo_strata = ifelse(Depth_m < breakpoint, "upper", "lower"))%>%
  group_by(Date, LakeID, hypo_strata)%>%
  dplyr::summarize(DO_tot = sum(DO_mass),#sum across all hypolimnetic depths
                   vol_tot = sum(IntervalVolume_m3),
                   DO_mgL_vol = DO_tot/vol_tot,#Divide by hypolimnetic volume
                   )%>%
  mutate(Year= year(Date))%>%
  group_by(LakeID, Year, hypo_strata)%>%
  filter(!is.na(DO_mgL_vol))%>%
  arrange(LakeID, Date)%>%
  mutate(low_point = ifelse(sum(DO_mgL_vol<1)==0,#Identify the lowest DO value for a given year
                            Date[which.min(DO_mgL_vol)],
                            first(Date[DO_mgL_vol<1])))%>%
  filter(is.na(low_point)|Date<=low_point)%>% #Remove days after the lowest DO value
  ungroup()%>%
  mutate(Year = year(Date))

length(unique(vw_do$LakeID)) #581 lakes left
```

Step 4: Model start of anoxia date using oxygen demand
```{r}
#Calculate the rate of change in volume-weighted concentrations using lm
DO_THRESH = 1.7

vw_do_demand <- vw_do%>%
  mutate(Year = year(Date),
         DOY = yday(Date))%>%
  group_by(Year, LakeID, hypo_strata)%>%
  dplyr::summarize(n = n(),
            DO_demand_mgLd = -lm(DO_mgL_vol~DOY)$coefficients[2],
            r2_vol = summary(lm(DO_mgL_vol~DOY))$r.squared,
            anoxic_onset = (DO_THRESH - lm(DO_mgL_vol~DOY)$coefficients[1]) / 
              lm(DO_mgL_vol~DOY)$coefficients[2])%>%
  filter(n>=3)#Need at least 3 points


#How many rows get removed by filtering so R2>0.5? ~500
removed_by_r2 <- vw_do_demand%>%
  filter(r2_vol>.5)

#How many rows get removed by filtering so oxygen demand is positive? 0
removed_by_pos <- removed_by_r2%>%
  filter(DO_demand_mgLd>0)

#Finish QAQC
good_hod <- vw_do_demand%>%
  group_by(LakeID, hypo_strata)%>%
  filter(!is.na(DO_demand_mgLd),
         r2_vol>0.5
         )%>%
  dplyr::summarize(n_neg = sum(DO_demand_mgLd<0),
                   n = n(),
                   pct = n_neg/n*100)%>%
  filter(pct<=10)

vw_do_demand_qaqc <- removed_by_pos%>%
  filter(LakeID %in% good_hod$LakeID)

vw_do_demand_qaqc %>%
  ggplot(aes(x = anoxic_onset))+
  geom_histogram()
```

Step 5: Empirically calculate start and end of anoxia date if it can be determined within a certain range (PROXIMITY)
```{r}
PROXIMITY = 7

empirical_anoxic_onset <- vw_do %>%
  group_by(LakeID, Year, hypo_strata) %>%
  filter(sum(DO_mgL_vol < DO_THRESH, na.rm = T) >= 1,
         sum(DO_mgL_vol > DO_THRESH, na.rm = T) >= 1) %>%
  mutate(onset = first(Date[DO_mgL_vol < DO_THRESH]),
         before = last(Date[Date<onset]),
         interval = as.numeric(onset-before),
         range = DO_mgL_vol[Date==before] - DO_mgL_vol[Date==onset],
         fraction = (DO_mgL_vol[Date==before] - DO_THRESH) / range) %>%
  filter(interval <= PROXIMITY) %>%
  summarize(anoxic_onset_data = unique(yday(before) + fraction * interval)) 

breaks <- full_with_thermo %>%
  full_join(lake_bats, by = c("LakeID","Depth_m"))%>%
  filter(!is.na(MaximumDepth_m),
         !is.na(hypo_depth),
         Depth_m > hypo_depth,
         !is.na(Area_m2)) %>%
  mutate(breakpoint = (MaximumDepth_m - hypo_depth)/2 + hypo_depth,
         hypo_strata = ifelse(Depth_m < breakpoint, "upper", "lower")) %>%
  group_by(LakeID, Year, hypo_strata, SurfaceArea_ha) %>%
  summarize(Area_m2 = max(Area_m2))

AF_two_layer <- vw_do_demand_qaqc %>%
  dplyr::select(Year, LakeID, anoxic_onset, hypo_strata) %>%
  rename(anoxic_onset_vhod = anoxic_onset) %>%
  full_join(empirical_anoxic_onset) %>%
  full_join(new_strat_end_model) %>%
  left_join(breaks) %>%
  mutate(anoxic_onset = ifelse(!is.na(anoxic_onset_data),
                               anoxic_onset_data,
                               anoxic_onset_vhod),
         anoxic_end = strat_end_new_model,
         duration = anoxic_end - anoxic_onset) %>%
  filter(!is.na(duration)) %>%
  dplyr::select(LakeID, Year, hypo_strata, Area_m2, duration, SurfaceArea_ha) %>%
  pivot_wider(names_from = hypo_strata, values_from = c(duration, Area_m2)) %>%
  filter(!is.na(duration_lower) & !is.na(duration_upper)) %>%
  mutate(duration_lower = ifelse(duration_lower < 0, 0, duration_lower),
         duration_upper = ifelse(duration_upper < 0, 0, duration_upper),
         duration_lower = duration_lower - duration_upper,
         AF_lower = duration_lower * Area_m2_lower / (SurfaceArea_ha*10000),
         AF_upper = duration_upper * Area_m2_upper / (SurfaceArea_ha*10000),
         AF = AF_lower + AF_upper) %>%
  dplyr::select(LakeID, Year, AF) %>%
  filter(!is.na(AF))
  
write.csv(AF_two_layer, "../Compiled data/AF - two layers.csv", row.names = F)
```
